version: '3'
services:
  web:
    image: "node:lts"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - VUE_APP_API_URL=api/
    command: "yarn serve"
    expose:
      - "8080"
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/conf.d/noun_development.conf:/etc/nginx/conf.d/default.conf