[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Boris Zalman <boris@zalman.online>"]

[tool.poetry.dependencies]
python = "*"
flask = "^1.0"
requests_oauthlib = "^1.2"
flask_cors = "^3.0"

[tool.poetry.dev-dependencies]
